# Generated by Django 5.1.3 on 2024-11-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IDRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number", models.CharField(max_length=13, unique=True)),
                ("gender", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                ("sa_citizen", models.BooleanField(default=True)),
                ("search_count", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("holiday_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("holiday_date", models.DateField()),
                ("holiday_type", models.CharField(max_length=50)),
                (
                    "id_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="id_search.idrecord",
                    ),
                ),
            ],
        ),
    ]
